language: node_js
node_js:
  - "10"
sudo: required
env: DISPLAY=':99.0'
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - wget
      - unzip

before_script:
  - wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - sh -e /etc/init.d/xvfb start
  - google-chrome --version
