language: node_js
node_js:
  - "10"
sudo: required
env: DISPLAY=':99.0'
dist: trusty

jobs:
  include:
    - name: "Linting"
      script: npm run lint

    - name: "Unit tests"
      script: npm run test:unit

    - name: "End to end tests"
      script:
        - npm run build:cdn
        - npm run test:e2e
      before_script:
        - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
        - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
        - unzip chromedriver_linux64.zip
        - sudo mv chromedriver /usr/local/bin
        - sh -e /etc/init.d/xvfb start
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
            - curl
            - unzip
